services:
  - type: web
    name: agentic-xai-backend
    env: python
    buildCommand: pip install -r requirements-simple.txt
    startCommand: python render-start.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 